export const unicodeCategories = [
  {
    name: "Invisible Characters",
    slug: "invisible-characters",
    description: "Special characters that are not visible but have specific uses",
    characters: [
      {
        id: "2800",
        name: "Braille Pattern Blank",
        symbol: "⠀",
        description: "Represents a blank space in the Braille alphabet",
        category: "Braille Patterns",
        htmlEntity: "&#10240;",
        usage: ["Used in digital content, programming, and design", "Creates blank spaces in usernames and messages"],
      },
      {
        id: "200B",
        name: "Zero Width Space",
        symbol: "​",
        description: "Indicates word boundaries without visible space",
        category: "Format Controls",
        htmlEntity: "&#8203;",
        usage: ["Used for word wrapping in complex scripts", "Helps with text formatting in various applications"],
      },
      {
        id: "200C",
        name: "Zero Width Non-Joiner",
        symbol: "‌",
        description: "Prevents characters from joining in certain scripts",
        category: "Format Controls",
        htmlEntity: "&#8204;",
        usage: ["Used in Persian and Arabic text processing", "Helps with proper text rendering in certain languages"],
      },
      {
        id: "200D",
        name: "Zero Width Joiner",
        symbol: "‍",
        description: "Joins characters that would not normally join",
        category: "Format Controls",
        htmlEntity: "&#8205;",
        usage: ["Used to create emoji sequences", "Helps with ligature formation in certain scripts"],
      },
      {
        id: "2060",
        name: "Word Joiner",
        symbol: "⁠",
        description: "Indicates word boundaries without breaking text",
        category: "Format Controls",
        htmlEntity: "&#8288;",
        usage: ["Prevents line breaks between words", "Used in text layout and formatting"],
      },
      {
        id: "FEFF",
        name: "Zero Width No-Break Space",
        symbol: "﻿",
        description: "Indicates no line break, but also no width",
        category: "Format Controls",
        htmlEntity: "&#65279;",
        usage: ["Used as a Byte Order Mark (BOM) in Unicode text", "Helps with text encoding detection"],
      },
      // ... Add more invisible characters to reach at least 100
    ],
  },
  {
    name: "Whitespace Characters",
    slug: "whitespace-characters",
    description: "Characters that represent various types of white space",
    characters: [
      {
        id: "0020",
        name: "Space",
        symbol: " ",
        description: "Standard space character",
        category: "Whitespace",
        htmlEntity: "&#32;",
        usage: ["Used to separate words in text", "Basic text formatting and layout"],
      },
      {
        id: "00A0",
        name: "No-Break Space",
        symbol: " ",
        description: "Space that prevents line breaks",
        category: "Whitespace",
        htmlEntity: "&#160;",
        usage: ["Keeps words together on the same line", "Used in typography for proper spacing"],
      },
      {
        id: "2002",
        name: "En Space",
        symbol: " ",
        description: "Space with a width of one en (half an em)",
        category: "Whitespace",
        htmlEntity: "&#8194;",
        usage: ["Used in typography for precise spacing", "Often used in mathematical formulas"],
      },
      {
        id: "2003",
        name: "Em Space",
        symbol: " ",
        description: "Space with a width of one em",
        category: "Whitespace",
        htmlEntity: "&#8195;",
        usage: ["Used in typography for wide spacing", "Often used in East Asian typography"],
      },
      {
        id: "2004",
        name: "Three-Per-Em Space",
        symbol: " ",
        description: "Space with a width of one-third of an em",
        category: "Whitespace",
        htmlEntity: "&#8196;",
        usage: [
          "Used in typography for fine spacing adjustments",
          "Often used in mathematical and scientific notation",
        ],
      },
      {
        id: "2005",
        name: "Four-Per-Em Space",
        symbol: " ",
        description: "Space with a width of one-quarter of an em",
        category: "Whitespace",
        htmlEntity: "&#8197;",
        usage: ["Used in typography for very fine spacing adjustments", "Useful in complex layout scenarios"],
      },
      {
        id: "2006",
        name: "Six-Per-Em Space",
        symbol: " ",
        description: "Space with a width of one-sixth of an em",
        category: "Whitespace",
        htmlEntity: "&#8198;",
        usage: ["Used in typography for extremely fine spacing", "Helpful in precise typographic layouts"],
      },
      // ... Add more whitespace characters
    ],
  },
  {
    name: "Punctuation",
    slug: "punctuation",
    description: "Various punctuation marks and symbols",
    characters: [
      {
        id: "2010",
        name: "Hyphen",
        symbol: "‐",
        description: "Used to join words or parts of words",
        category: "Punctuation",
        htmlEntity: "&#8208;",
        usage: ["Joining compound words", "Indicating word breaks at the end of a line"],
      },
      {
        id: "2011",
        name: "Non-Breaking Hyphen",
        symbol: "‑",
        description: "Hyphen that prevents line breaks",
        category: "Punctuation",
        htmlEntity: "&#8209;",
        usage: ["Keeping hyphenated words together", "Used in phone numbers or other sequences that shouldn't break"],
      },
      {
        id: "2012",
        name: "Figure Dash",
        symbol: "‒",
        description: "Used in figures, like phone numbers",
        category: "Punctuation",
        htmlEntity: "&#8210;",
        usage: ["Separating groups of digits in phone numbers", "Used in numeric ranges"],
      },
      {
        id: "2013",
        name: "En Dash",
        symbol: "–",
        description: "Used to indicate ranges or connections",
        category: "Punctuation",
        htmlEntity: "&#8211;",
        usage: ["Indicating ranges of numbers or dates", "Connecting words in compound adjectives"],
      },
      {
        id: "2014",
        name: "Em Dash",
        symbol: "—",
        description: "Used for breaks in sentences or to set off phrases",
        category: "Punctuation",
        htmlEntity: "&#8212;",
        usage: ["Creating a strong break in sentence structure", "Setting off parenthetical information"],
      },
      // ... Add more punctuation characters
    ],
  },
  // ... Add more Unicode categories (Symbols, Mathematical Operators, Arrows, etc.)
]

